version: 1.0.{build}
image: Visual Studio 2017
cache: packages -> **\package.config
build_script:
- cmd: >-
    nuget restore Hasher.sln && ^
    msbuild Hasher.sln /p:Configuration=Release /p:Platform="Any CPU" && ^
    copy Hasher\bin\Release\Hasher.zip Hasher.zip && ^
    copy Bootstrapper\bin\Release\HasherInstaller.exe HasherInstaller.exe && ^
    msbuild Hasher.sln /p:Configuration=Release /p:Platform=x64 && ^
    copy Hasher\bin\x64\Hasher.amd64.zip Hasher.amd64.zip && ^
    copy Bootstrapper\bin\x64\Release\HasherInstaller.exe HasherInstaller.amd64.exe
artifacts:
- path: Hasher.zip
- path: HasherInstaller.exe
- path: Hasher.amd64.zip
- path: HasherInstaller.amd64.exe
