version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x86
- x64
cache: packages -> **\packages.config
before_build:
- cmd: nuget restore
build:
  project: Hasher.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: appveyor PushArtifact Hasher\bin\%PLATFORM%\Release\Hasher.zip -FileName Hasher.zip
- cmd: appveyor PushArtifact Bootstrapper\bin\%PLATFORM%\Release\HasherInstaller.exe -FileName HasherInstaller.exe
