version: 1.0.{build}
image: Visual Studio 2017
cache:
  - packages -> **\packages.config
configuration: Release
platform:
  - x86
  - x64
before_build:
  - nuget restore
build:
  parallel: true
  project: Hasher.sln
  verbosity: normal
after_build:
  - cmd: copy Hasher\bin\$(configuration)\Hasher.zip Hasher.zip
  - cmd: copy Bootstrapper\bin\$(configuration)\HasherInstaller.exe HasherInstaller.exe
  - cmd: copy Hasher\bin\x64\$(configuration)\Hasher.amd64.zip Hasher.amd64.zip
  - cmd: copy Bootstrapper\bin\x64\$(configuration)\HasherInstaller.amd64.exe HasherInstaller.amd64.exe
artifacts:
  - path: Hasher.zip
  - path: HasherInstaller.exe
  - path: Hasher.amd64.zip
  - path: HasherInstaller.amd64.exe
