version: 1.0.{build}
image: Visual Studio 2017
cache: packages -> **\package.config
build_script:
- cmd: >-
    nuget restore Hasher.sln

    msbuild Hasher.sln /p:Configuration=Release /p:Platform="Any CPU"

    copy Hasher\bin\Release\Hasher.zip Hasher.zip

    copy SetupProject\bin\x86\Release\HasherInstaller.msi HasherInstaller.msi

    msbuild Hasher.sln /p:Configuration=Release /p:Platform=x64

    copy Hasher\bin\x64\Hasher.amd64.zip Hasher.amd64.zip

    copy SetupProject\bin\x64\Release\HasherInstaller.msi HasherInstaller.amd64.msi
artifacts:
- path: Hasher.zip
- path: Hasher.msi
- path: Hasher.amd64.zip
- path: Hasher.amd64.msi
